# Basic Site Settings
locale                   : "en-US"
title                    : "Mukhtarat·Botakhaze's Personal Website"
title_separator          : "-"
name                     : &name "Mukhtarat·Botakhaze"
description              : &description "Undergraduate student at Fuzhou University, focused on software engineering and data science."
url                      : https://Victor-Bayim.github.io # 这是你的 GitHub Pages URL
baseurl                  : "" 
repository               : "Victor-Bayim/Victor.github.io" # 这是你的仓库名称

# Site Author - 个人信息
author:
  avatar           : "toux.png" # 上传的头像文件名
  name             : "Mukhtarat·Botakhaze"
  bio              : "Undergraduate student at Fuzhou University, studying software engineering and data science."
  location         : "Fuzhou, China"
  employer         : "Fuzhou University"
  email            : "2506976721@qq.com" 

  # Academic websites
  googlescholar    : "https://scholar.google.com" # 如果有 Google Scholar 页面，替换为你的链接
  orcid            : "http://orcid.org/yourorcidurl" # 如果有 ORCID 页面，替换为你的 ORCID URL

  # Repositories and software development
  github           : "Victor-Bayim" # 这是你的 GitHub 用户名

# Site Settings
breadcrumbs              : false
future                   : true
read_more                : "disabled"
comments:
  provider               : false
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  moderation             : true

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "your-twitter-username" # 如果有 Twitter，替换为你的用户名

# Analytics
analytics:
  provider               : "false"

# Markdown Processing
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # 修改为你的时区

